name: Subir Comentarios de Reunion DBO

on:
  workflow_dispatch: # Permite ejecución manual y desde Apps Script

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Uploader Script
        run: python meeting_uploader.py
